# ss
trigger:
  ref:
    - refs/heads/master
    - refs/tags/*

kind: pipeline
type: exec
name: default

platform:
  os: darwin

steps:
  - name: yarn
    commands:
      - whoami
      - yarn
  - name: run on emu
    commands:
      - npx rnv run -p web -e next
